services:
  broker:
    image: apache/kafka-native
    hostname: kafka
    container_name: kafka-native
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
      - 2181:2181
